abstract: An SMS::Send driver for the myvodafone.com.au website
author: 'Adam Kennedy <cpan@ali.as>, L<http://ali.as/>'
build_requires:
  File::Spec: 0.80
  Test::More: 0.47
distribution_type: module
generated_by: Module::Install version 0.50
license: perl
name: SMS-Send-AU-MyVodafone
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  IO::Socket::SSL: 0.97
  LWP: 5.69
  SMS::Send: 0.02
  WWW::Mechanize: 1.06
  perl: 5.005
version: 0.02
